export const DB = "vesting"
export const WEEKLY_REWARD_INFO_COLLECTION = "rewardscollections"
export const USER_INFO_COLLECTION = "user_info"
export const URL = "mongodb://localhost:27017/"
export const BURRY_BONE_COLLECTION = "buryBoneCollection"
export const BURRY_LEASH_COLLECTION = "buryLeashCollection"
export const BURRY_SHIB_COLLECTION = "buryShibCollection"
export const TOPDOG_COLLECTION = "topDogCollection"