export const DB = "vesting"
export const WEEKLY_REWARD_INFO_COLLECTION = "rewardscollections"
export const USER_INFO_COLLECTION = "user_info_v2"
export const URL = "mongodb://localhost:27017/"
export const BURRY_BONE_COLLECTION = "burybonecollections"
export const BURRY_LEASH_COLLECTION = "buryleashcollections"
export const BURRY_SHIB_COLLECTION = "buryshibcollections"
export const TOPDOG_COLLECTION = "topdogcollections"